package hu.blackbelt.judo.tatami.workflow.osgi;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import static hu.blackbelt.judo.tatami.workflow.osgi.TransformationConstants.*;

/**
 * This configuration respresents with default bundles all of the transformation bundles are usable with Tatami.
 */
@ObjectClassDefinition(name="Transformation bundle tracker configurations")
public @interface TransformationBundleTrackerConfig {
    @AttributeDefinition(
            name = "Transformation bundles",
            description = "The transformation bundles used to resolve scripts for workflow steps."
    )
    String transformationBundles() default
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_RDBMS_TO_LIQUIBASE + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_RDBMS_2_LIQUIBASE + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + MANIFEST_TAG_RDBMS_TO_LIQUIBASE_SCRIPT_ROOT + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_PSM_2_MEASURE + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_PSM_2_MEASURE + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + MANIFEST_TAG_PSM_2_MEASURE_SCRIPT_ROOT + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_PSM_2_ASM + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_PSM_2_ASM + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + MANIFEST_TAG_PSM_2_ASM_SCRIPT_ROOT + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_ESM_2_PSM + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_ESM_2_PSM + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + MANIFEST_TAG_ESM_2_PSM_SCRIPT_ROOT + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_ASM_2_RDBMS + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_ASM_2_RDBMS + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + MANIFEST_TAG_ASM_2_RDBMS_SCRIPT_ROOT + SEMI_COLON + MODEL_HEADER_NAME + EQ + MANIFEST_TAG_ASM_2_RDBMS_MODEL_ROOT + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_ASM_2_OPENAPI + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_ASM_2_OPENAPI + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + TRAANSFORMATION_ASM_2_RDBMS + SCRIPT_ROOT_POSTFIX + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_ASM_2_JAXRSAPI + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_ASM_2_JAXRSAPI + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + TRAANSFORMATION_ASM_2_RDBMS + SCRIPT_ROOT_POSTFIX + COMA +
                TRANSFORMATION_NAME + EQ + TRAANSFORMATION_ASM_2_SDK + SEMI_COLON + BUNDLE_SYMBOLIC_NAME + EQ + BUNDLE_SYMBOLIC_NAME_JUDO_TATAMI_ASM_2_SDK + SEMI_COLON + SCRIPT_HEADER_NAME + EQ + TRAANSFORMATION_ASM_2_RDBMS + SCRIPT_ROOT_POSTFIX;
}
